#!/usr/bin/env python3
"""Approximate PSG transcription of the original MP3 music loops.

The original soundtrack is two short tonal loops (MainMusic 12.8 s, NightMusic 8.7 s).
This tool decodes them with ffmpeg, picks the dominant pitch in two bands every 1/30 s
(melody band and bass band), cleans the pitch track and run-length encodes it as
(midi note, ticks) pairs for the 2-voice PSG player in src/platform/msx_audio.c.
It is an *automatic approximation*, not a hand-made arrangement (see docs/PORTING.md).
"""
import os, subprocess, sys, wave, tempfile
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "original", "src", "assets")
OUT = os.path.join(ROOT, "src", "data")
SR = 22050
TICK = 1.0 / 30
WIN = 2048


def decode(name):
    tmp = os.path.join(tempfile.gettempdir(), name + ".wav")
    subprocess.check_call(["ffmpeg", "-loglevel", "error", "-y", "-i", os.path.join(ASSETS, name + ".mp3"),
                           "-ac", "1", "-ar", str(SR), tmp])
    w = wave.open(tmp)
    x = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(float)
    return x


def track(x, lo, hi, rel_thr):
    hop = int(SR * TICK)
    ticks = len(x) // hop
    freqs = np.fft.rfftfreq(WIN, 1 / SR)
    band = (freqs >= lo) & (freqs <= hi)
    win = np.hanning(WIN)
    peaks = []
    notes = []
    for t in range(ticks):
        c = t * hop + hop // 2
        s = max(0, c - WIN // 2)
        seg = x[s:s + WIN]
        if len(seg) < WIN:
            seg = np.pad(seg, (0, WIN - len(seg)))
        sp = np.abs(np.fft.rfft(seg * win)) * band
        k = int(np.argmax(sp))
        peaks.append(sp[k])
        notes.append(69 + 12 * np.log2(freqs[k] / 440) if freqs[k] > 0 else 0)
    peaks = np.array(peaks)
    thr = peaks.max() * rel_thr
    out = []
    for p, n in zip(peaks, notes):
        out.append(int(round(n)) if p >= thr else 0)
    # median filter (3 ticks) to remove blips, then drop notes shorter than 2 ticks
    sm = out[:]
    for i in range(1, len(out) - 1):
        a, b, c = out[i - 1], out[i], out[i + 1]
        if a == c and b != a:
            sm[i] = a
    return sm


def rle(seq, max_run=255):
    res = []
    i = 0
    while i < len(seq):
        j = i
        while j < len(seq) and seq[j] == seq[i] and j - i < max_run:
            j += 1
        res.append((seq[i], j - i))
        i = j
    return res


def emit(name, melody, bass):
    def arr(label, seq):
        pairs = rle(seq)
        flat = []
        for n, d in pairs:
            n = max(0, min(95, n)) if n else 0
            if n and n < 24:
                n += 12 * ((24 - n + 11) // 12)
            flat += [n, d]
        flat.append(0xFF)
        lines = ["\t" + ",".join("%d" % v for v in flat[i:i + 24]) + "," for i in range(0, len(flat), 24)]
        return "static const unsigned char %s[] = {\n%s\n};\n" % (label, "\n".join(lines)), len(flat)
    a, na = arr("s_%s_v0" % name, melody)
    b, nb = arr("s_%s_v1" % name, bass)
    return a + b, na + nb


def main():
    out = ['// GENERATED by tools/gen_music.py from original MP3 loops (automatic approximation)',
           '#include "music_data.h"', ""]
    total = 0
    for name in ("MainMusic", "NightMusic"):
        x = decode(name)
        x = x / (np.abs(x).max() + 1e-9)
        mel = track(x, 260, 2200, 0.18)
        bas = track(x, 50, 260, 0.18)
        code, n = emit(name, mel, bas)
        out.append(code)
        total += n
        print(name, "ticks:", len(mel), "bytes:", n)
    out.append("const MusicTrack g_MusicTracks[2] = {")
    out.append("\t{ { s_MainMusic_v0, s_MainMusic_v1 } },")
    out.append("\t{ { s_NightMusic_v0, s_NightMusic_v1 } },")
    out.append("};")
    open(os.path.join(OUT, "music_data.c"), "w").write("\n".join(out) + "\n")
    print("total bytes", total)


if __name__ == "__main__":
    main()
