#pragma once
// GENERATED by tools/gen_assets.py
extern const unsigned char g_Gfx_logo[];
#define GFX_LOGO_W 32
#define GFX_LOGO_H 6
extern const unsigned char g_Gfx_logo2[];
#define GFX_LOGO2_W 32
#define GFX_LOGO2_H 6
extern const unsigned char g_Gfx_logo_small[];
#define GFX_LOGO_SMALL_W 16
#define GFX_LOGO_SMALL_H 3
extern const unsigned char g_Gfx_logo_small2[];
#define GFX_LOGO_SMALL2_W 16
#define GFX_LOGO_SMALL2_H 3
extern const unsigned char g_Gfx_ministry[];
#define GFX_MINISTRY_W 13
#define GFX_MINISTRY_H 9
extern const unsigned char g_Gfx_presses[];
#define GFX_PRESSES_W 31
#define GFX_PRESSES_H 8
extern const unsigned char g_Gfx_meter[];
#define GFX_METER_W 5
#define GFX_METER_H 5
