// GENERATED by tools/gen_assets.py from original/src/NewsItem.as - do not edit
#include "../game_data.h"

const NewsDef g_News[NEWS_COUNT] = { // NEWS_COUNT == 71
	{ 1, 3, 1, 1, "The rebellion has been crushed. Peace returns to all sectors", "Rebellion Crushed, Peace Restored!" }, // 0
	{ 3, -1, 0, 1, "*** ####....##...####..## ***", 0 }, // 1
	{ 4, -1, 0, 1, "*** Est#blishing secure chan#el. Aw#it further# comm###ication ***", 0 }, // 2
	{ 6, -1, 0, 1, "*** #Please hear me. I am Kurstov, leader of#the rebellion. We need your help. ***", 0 }, // 3
	{ 7, -1, 0, 1, "*** We can rescue your family. Sow disloyalty to strengthen the rebels. You have 4 days. ***", 0 }, // 4
	{ 8, -1, 0, 1, "*** Please help us. The government's tyranny must end! Place negative articles! ***|*** Your family will soon be safe! Drop the public's loyalty to -30 and get 1000 readers in 3 days! ***|*** It's working! Your efforts have strengthened us unimaginably! ***", 0 }, // 5
	{ 9, -1, 0, 1, "*** The government cannot win! Seal their fate! Place negative articles! ***|*** Your family's safety is assured! Convince 1000 readers to be disloyal in 2 days! ***|*** Yes! Our operations are in order. Soon we overthrow! ***", 0 }, // 6
	{ 10, -1, 0, 1, "*** We have no time! The people must be free! Spread negative news! ***|*** Our time is at hand! Hurry! Get 1000 readers with -30 loyalty by the end of today! ***|*** Oh glorious day! We strike at sundown. Prepare yourself! ***", 0 }, // 7
	{ 7, 100, 1, 1, "Terrorist rebel hideout near Central Chem destroyed", "Rebels Routed At Factory!" }, // 8
	{ 8, 100, -1, 1, "Rebels at Central Chem sabotage important machinary", "Factory Sabotaged!" }, // 9
	{ 9, 100, 1, 1, "Terrorist 2nd-in-command captured. Renounces fight against [GOV]", "Terrorist Leader Buckles!" }, // 10
	{ 10, 100, -1, 1, "Rebels regroup in western towns. Growing in strength and number.", "Rebels Gaining Support!" }, // 11
	{ 0, 0, 1, 1, "[GOV] forces have destroyed Antegria's illegal satellites", "[GOV] Downs Enemy Satellite!" }, // 12
	{ 0, 0, 1, 1, "[GOV] borders have been reinforced with 200,000 additional troops", "Borders Reinforced!" }, // 13
	{ 0, 0, 1, 1, "State-of-the-art military spy satellites now used to reduce crime", "Keeping An Eye On Crime!" }, // 14
	{ 0, 0, 1, 1, "[GOV] Navy commissions an additional 500 destroyers to patrol coast", "Safeguarding The Coasts!" }, // 15
	{ 0, 0, 1, 1, "[GOV] Air Force tactical fighter sets new speed record", "Faster Fighter Flown!" }, // 16
	{ 0, 0, 1, 1, "Multiple terrorist cells in central district foiled in operation", "Central Terrorists Terminated!" }, // 17
	{ 0, 0, 1, 1, "[GOV] Army 5th Divison shuts down bomb factory in northern mountains", "Bomb Factory Found, Destroyed!" }, // 18
	{ 0, 0, 1, 1, "[GOV] soldiers strongest in the world according to latest tests", "Our Boys Are the Best!" }, // 19
	{ 0, 0, 1, 1, "Peace enforcement squad rounds up 200 terrorist rebels", "Peace Restored, Rebels Captured!" }, // 20
	{ 0, 0, -1, 1, "40,000 gallons of military gasoline stolen from western bases", "Military Gas Gone!" }, // 21
	{ 0, 0, -1, 1, "Critical oil fields in the north have been sabotaged", "Pipelines Crippled!" }, // 22
	{ 0, 0, -1, 1, "Terrorist bomb explodes on northern bay ferry. 600 people missing", "Explosion Rocks The Seas!" }, // 23
	{ 0, 0, -1, 1, "[GOV] Air Force tactical fighter test flight ends in crash. Crew lost", "Futuristic Fight Crashes, Burns!" }, // 24
	{ 0, 0, -1, 1, "[GOV] Navy identifies critical fault in all operational submarines", "Our Subs Are Faulty!" }, // 25
	{ 0, 0, -1, 1, "The top general in charge of southern forces has died suddenly", "General Dies Overnight!" }, // 26
	{ 0, 0, -1, 1, "Antegria secret code remains unbreakable. Top [GOV] minds are flumoxed", "The Enemy's Unbreakable Code!" }, // 27
	{ 0, 0, -1, 1, "Tank production falls behind schedule. Poor factory conditions blamed", "Tanking Tanks!" }, // 28
	{ 0, 0, -1, 1, "Worldwide survey finds [GOV] soldiers worst trained, with worst aim", "Our Boys Can't Fire Straight!" }, // 29
	{ 0, 0, -1, 1, "Antegria Navy sinks [GOV] battleship off eastern coast", "[GOV] Battleship Bested!" }, // 30
	{ 0, 0, 1, 0, "The Honorable and Great Leader awarded Lifetime Glory medal", "A Lifetime of Glory!" }, // 31
	{ 0, 0, 1, 0, "Agricultural output from the farming sector doubles for 10th straight month", "More Corn Than Air!" }, // 32
	{ 0, 0, 1, 0, "Income reallocation scheme contributes 400 million to schools. Proves system works", "Education Spending Up!" }, // 33
	{ 0, 0, 1, 0, "Latest polls show broad satisfaction with government leaders", "Politics Polls Positive!" }, // 34
	{ 0, 0, 1, 0, "Newest regional administrator fights for worker's rights", "Power To The People!" }, // 35
	{ 0, 0, -1, 0, "Party officials have voted to adjust ration quotas for all orphans", "Less Food For Orphans" }, // 36
	{ 0, 0, -1, 0, "The Honorable and Great Leader photographed in women's clothes", "Great Leader, In A Dress!" }, // 37
	{ 0, 0, -1, 0, "30,000 teachers and academics reassigned to more useful labor tasks", "Educators Punished For Being Smart!" }, // 38
	{ 0, 0, -1, 0, "Local citizen council votes will be eliminated in favor of suggestive comments", "Local Councils Lose Vote!" }, // 39
	{ 0, 0, -1, 0, "Yearly donations to the state must increase to support growing government oversight", "Taxes Rise For 8th Year!" }, // 40
	{ 0, 0, 0, 1, "Weather: Skies and temperatures will remain calm today", "Another Sunny Day!" }, // 41
	{ 0, 0, 0, 1, "Weather: Storms predicted to wash western coast out to sea", "Western Storms Threaten Coast!" }, // 42
	{ 0, 0, 0, 1, "Weather: Forecast expects heavy rains in the north and east", "Showers Rain Down!" }, // 43
	{ 0, 0, 0, 1, "Weather: Expect unseasonal snow in the south", "Blizzard Incoming?" }, // 44
	{ 0, 0, 0, 1, "Weather: Sunny morning and cloudy evening for the day", "Warm To Cloudy!" }, // 45
	{ 0, 0, 0, 1, "Weather: Light showers throughout the day", "Warm To Cloudy This Week!" }, // 46
	{ 0, 0, 0, 1, "Weather: Hurricane-level winds spotted off eastern coast", "Eastern Hurricanes Return!" }, // 47
	{ 0, 0, 0, 1, "Weather: Clear skies and no sign of rain", "Another Dry Day!" }, // 48
	{ 0, 0, 0, 1, "Weather: Freezing sleet and snow expected in northern mountains", "Buckle Down For Ice!" }, // 49
	{ 0, 0, 0, 1, "Weather: Tropical breezes blow across southeastern coast", "Sea Breeze Incoming!" }, // 50
	{ 0, 0, 1, 1, "[GOV] National Team has won the global football tournament", "[GOV] Wins Football Crown!" }, // 51
	{ 0, 0, 1, 1, "Antegria ski team soundly defeated by [GOV] crew", "[GOV] Defeats Antegria Skiers!" }, // 52
	{ 0, 0, 1, 1, "Tennis star Restojiu powers through semifinal brackets", "Tennis Star Advances!" }, // 53
	{ 0, 0, 1, 1, "Young [GOV] atheletes dominate track and field. May win Olympic gold", "Our Young Heroes!" }, // 54
	{ 0, 0, 1, 1, "Skilled [GOV] baseball team finishes record season. Thanks Leader for support", "Baseball Success Sealed!" }, // 55
	{ 0, 0, 0, 1, "Championship weight lifter Lekshou retires due to crippling injury", "Muscleman Retires!" }, // 56
	{ 0, 0, -1, 1, "[GOV] National Football Team has lost the regional finals to Antegria", "[GOV] Football Stumbles!" }, // 57
	{ 0, 0, -1, 1, "Entire [GOV] National Hockey team killed in plane crash", "Tragedy Strikes Hockey!" }, // 58
	{ 0, 0, -1, 1, "Athletic training in [GOV] is years behind the competition", "Our Athletes: Behind The Curve?" }, // 59
	{ 0, 0, -1, 1, "National kayaking team has defected to Antegria", "Kayaking For The Enemy!" }, // 60
	{ 0, 0, 1, 1, "Cherrywood's newest stars attended recent gala ball to honor verterans", "Stars Dance For Vets!" }, // 61
	{ 0, 0, 1, 1, "New fall TV programming will focus on [GOV]'s rebuilding", "Fall TV Revealaed!" }, // 62
	{ 0, 0, 1, 1, "Beloved children's book \"Mumpit Mush\" finally coming to the big screen", "Mumpit Mush Is Coming!" }, // 63
	{ 2, -1, 1, 1, "Superstars Chad and Jenlyn preparing for Cherrywood wedding tomorrow", "C&J To Tie the Knot!" }, // 64
	{ 3, -1, 1, 1, "Superstars Chad and Jenlyn marry in extravagant festival", "C&J Finally Hitched!" }, // 65
	{ 0, 0, 0, 1, "\"My butt is not too fat, just right\" claims TV star Aprelica", "Butt Within Spec!" }, // 66
	{ 0, 0, -1, 1, "Reality star Mestonda found dead from apparent overdose", "Reality Star Overdoses!" }, // 67
	{ 0, 0, -1, 1, "Fashion designer CrevyCrevy has defected to Antegria", "Fashion Icon Defects!" }, // 68
	{ 0, 0, -1, 1, "Mega-group HugginBoyz admits to not singing on any albums, can barely dance", "HugginBoyz: Talentless After All!" }, // 69
	{ 6, -1, -1, 1, "Superstars Chad and Jenlyn file for divorce. Both claim infidelity", "C&J Fairytale Ends!" }, // 70
};
