// GENERATED by tools/gen_assets.py - do not edit
#pragma once
#define GFX_PALETTE_INIT { 0x12, 0x02, 0x11, 0x01, 0x76, 0x07, 0x33, 0x03, 0x72, 0x03, 0x07, 0x04, 0x72, 0x05, 0x71, 0x03, 0x13, 0x04, 0x55, 0x05, 0x64, 0x05, 0x34, 0x03, 0x46, 0x05, 0x53, 0x04, 0x66, 0x06, 0x34, 0x04 }
#define GFX_ATLAS_FIRST_SEG 4
#define GFX_ATLAS_SEGS 12
#define GFX_ATLAS_LINES 736
#define GFX_ATLAS_Y0 256
#define GFX_LOGO_SEG 16
#define GFX_LOGO_W 152
#define GFX_LOGO_H 98
#define GFX_CELL_W 24
#define GFX_CELL_H 32
#define GFX_CELLS_PER_ROW 10
#define CELL_CARD 0
#define CELL_BACK 52
#define CELL_BLANK 53
#define CELL_PLANET 60
#define CELL_JOKER 80
#define CELL_TAROT 168
#define FONT_ROWS 9
#define BLIND_ICON_COUNT 30
// blind icon rows (16px each) in atlas column x=240: bl_small=0, bl_big=1, bl_hook=2, bl_ox=3, bl_house=4, bl_wall=5, bl_wheel=6, bl_arm=7, bl_club=8, bl_fish=9, bl_psychic=10, bl_goad=11, bl_water=12, bl_window=13, bl_manacle=14, bl_eye=15, bl_mouth=16, bl_plant=17, bl_serpent=18, bl_pillar=19, bl_needle=20, bl_head=21, bl_tooth=22, bl_flint=23, bl_mark=24, bl_final_acorn=25, bl_final_leaf=26, bl_final_vessel=27, bl_final_heart=28, bl_final_bell=29
