"""Content selection for the MSX port: which jokers / consumables are carried over.

Keys are Balatro's own center keys (original/game.lua P_CENTERS). Order here = order of the
generated C tables (J_xxx enum) and of the graphic cells in the VRAM atlas."""

JOKERS = [
 # tier 1/2 hand-type jokers
 "joker","greedy_joker","lusty_joker","wrathful_joker","gluttenous_joker",
 "jolly","zany","mad","crazy","droll","sly","wily","clever","devious","crafty",
 "half","stencil","four_fingers","credit_card","banner","mystic_summit","misprint",
 "raised_fist","fibonacci","scary_face","abstract","delayed_grat","pareidolia",
 "gros_michel","even_steven","odd_todd","scholar","business","supernova","ride_the_bus",
 "space","egg","blue_joker","splash","shortcut","smeared","golden","juggler","drunkard",
 "card_sharp","photograph","walkie_talkie","smiley","runner","ice_cream","square","popcorn",
 "green_joker","cavendish","blackboard","bull","bootstraps","shoot_the_moon","baron",
 "reserved_parking","faceless","to_the_moon","burglar","turtle_bean","stuntman","merry_andy",
 "troubadour","duo","trio","family","order","tribe","swashbuckler","constellation","cloud_9",
 "rocket","satellite","bloodstone","arrowhead","onyx_agate","rough_gem","flower_pot",
 "seeing_double","acrobat","mr_bones","wee","ramen","todo_list",
]

# planet cards, in the order of the hand types they level (see HAND_* in the C code)
PLANETS = [
 ("pluto",   "High Card"), ("mercury","Pair"), ("uranus","Two Pair"), ("venus","Three of a Kind"),
 ("saturn",  "Straight"), ("jupiter","Flush"), ("earth","Full House"), ("mars","Four of a Kind"),
 ("neptune", "Straight Flush"), ("planet_x","Five of a Kind"), ("ceres","Flush House"), ("eris","Flush Five"),
]

TAROTS = [
 "fool","magician","high_priestess","empress","emperor","heirophant","lovers","chariot","justice","hermit",
 "wheel_of_fortune","strength","hanged_man","death","temperance","devil","tower","star","moon","sun","judgement","world",
]

# normal bosses (x,y row in BlindChips.png) - filled by gen_data from game.lua

# Short effect texts shown on the MSX UI (own wording; effects verified against original/card.lua).
JOKER_DESC = {
 "joker": "+4 Mult",
 "greedy_joker": "Played Diamonds give +3 Mult", "lusty_joker": "Played Hearts give +3 Mult",
 "wrathful_joker": "Played Spades give +3 Mult", "gluttenous_joker": "Played Clubs give +3 Mult",
 "jolly": "+8 Mult if hand has a Pair", "zany": "+12 Mult if hand has Three of a Kind",
 "mad": "+10 Mult if hand has Two Pair", "crazy": "+12 Mult if hand has a Straight",
 "droll": "+10 Mult if hand has a Flush",
 "sly": "+50 Chips if hand has a Pair", "wily": "+100 Chips if hand has Three of a Kind",
 "clever": "+80 Chips if hand has Two Pair", "devious": "+100 Chips if hand has a Straight",
 "crafty": "+80 Chips if hand has a Flush",
 "half": "+20 Mult if hand has 3 or fewer cards",
 "stencil": "X1 Mult per empty Joker slot (itself counts)",
 "four_fingers": "Flushes and Straights need only 4 cards",
 "credit_card": "Go up to -$20 in debt",
 "banner": "+30 Chips per remaining discard",
 "mystic_summit": "+15 Mult when 0 discards remain",
 "misprint": "+0 to +23 Mult at random",
 "raised_fist": "Double the rank of your lowest held card is added to Mult",
 "fibonacci": "Scored A,2,3,5,8 give +8 Mult",
 "scary_face": "Scored face cards give +30 Chips",
 "abstract": "+3 Mult per Joker owned",
 "delayed_grat": "Earn $2 per discard left if none was used this round",
 "pareidolia": "All cards count as face cards",
 "gros_michel": "+15 Mult. 1 in 6 to be destroyed each round",
 "even_steven": "Scored 10,8,6,4,2 give +4 Mult",
 "odd_todd": "Scored A,9,7,5,3 give +31 Chips",
 "scholar": "Scored Aces give +20 Chips and +4 Mult",
 "business": "Scored face cards: 1 in 2 chance to earn $2",
 "supernova": "+Mult equal to times this hand type was played",
 "ride_the_bus": "+1 Mult per hand in a row without a scoring face card",
 "space": "1 in 4 chance to level up the played hand",
 "egg": "Gains $3 sell value each round",
 "blue_joker": "+2 Chips per card left in deck",
 "splash": "Every played card counts for scoring",
 "shortcut": "Straights may skip one rank",
 "smeared": "Hearts=Diamonds, Spades=Clubs",
 "golden": "Earn $4 at end of round",
 "juggler": "+1 hand size",
 "drunkard": "+1 discard each round",
 "card_sharp": "X3 Mult if this hand type was already played this round",
 "photograph": "First scored face card gives X2 Mult",
 "walkie_talkie": "Scored 10s and 4s give +10 Chips and +4 Mult",
 "smiley": "Scored face cards give +5 Mult",
 "runner": "Gains +15 Chips if hand has a Straight",
 "ice_cream": "+100 Chips, -5 Chips per hand played",
 "square": "Gains +4 Chips if played hand has exactly 4 cards",
 "popcorn": "+20 Mult, -4 Mult each round",
 "green_joker": "+1 Mult per hand played, -1 per discard",
 "cavendish": "X3 Mult. 1 in 1000 to be destroyed each round",
 "blackboard": "X3 Mult if all held cards are Spades or Clubs",
 "bull": "+2 Chips per $1 you have",
 "bootstraps": "+2 Mult per $5 you have",
 "shoot_the_moon": "Each Queen held in hand gives +13 Mult",
 "baron": "Each King held in hand gives X1.5 Mult",
 "reserved_parking": "Each face card held: 1 in 2 chance to earn $1",
 "faceless": "Earn $5 if 3+ face cards are discarded at once",
 "to_the_moon": "Earn an extra $1 interest per $5 you hold",
 "burglar": "+3 Hands, lose all discards on Blind select",
 "turtle_bean": "+5 hand size, -1 each round",
 "stuntman": "+250 Chips, -2 hand size",
 "merry_andy": "+3 discards each round, -1 hand size",
 "troubadour": "+2 hand size, -1 hand each round",
 "duo": "X2 Mult if hand has a Pair", "trio": "X3 Mult if hand has Three of a Kind",
 "family": "X4 Mult if hand has Four of a Kind", "order": "X3 Mult if hand has a Straight",
 "tribe": "X2 Mult if hand has a Flush",
 "swashbuckler": "Adds the sell value of other Jokers to Mult",
 "constellation": "Gains X0.1 Mult per Planet card used",
 "cloud_9": "Earn $1 per 9 in your full deck each round",
 "rocket": "Earn $1 each round; +$2 payout after each Boss",
 "satellite": "Earn $1 per unique Planet used, each round",
 "bloodstone": "Scored Hearts: 1 in 2 chance for X1.5 Mult",
 "arrowhead": "Scored Spades give +50 Chips",
 "onyx_agate": "Scored Clubs give +7 Mult",
 "rough_gem": "Scored Diamonds earn $1",
 "flower_pot": "X3 Mult if hand scores a Diamond, Club, Heart and Spade",
 "seeing_double": "X2 Mult if hand has a scoring Club and a card of another suit",
 "acrobat": "X3 Mult on the final hand of the round",
 "mr_bones": "Prevents death if chips are at least 25% of the Blind. Self-destructs",
 "wee": "Gains +8 Chips when a scored 2 is played",
 "ramen": "X2 Mult, loses X0.01 per card discarded",
 "todo_list": "Earn $4 if the hand is the listed type. Type changes each round",
}

TAROT_DESC = {
 "fool": "Creates the last Tarot or Planet card used",
 "high_priestess": "Creates up to 2 random Planet cards",
 "emperor": "Creates up to 2 random Tarot cards",
 "hermit": "Doubles your money (max +$20)",
 "strength": "Raises rank of up to 2 selected cards by 1",
 "hanged_man": "Destroys up to 2 selected cards",
 "death": "Select 2 cards: the left one becomes a copy of the right one",
 "temperance": "Gives the total sell value of your Jokers (max $50)",
 "star": "Converts up to 3 selected cards to Diamonds",
 "moon": "Converts up to 3 selected cards to Clubs",
 "sun": "Converts up to 3 selected cards to Hearts",
 "world": "Converts up to 3 selected cards to Spades",
 "judgement": "Creates a random Joker",
 "magician": "Enhances up to 2 selected cards to Lucky Cards",
 "empress": "Enhances up to 2 selected cards to Mult Cards",
 "heirophant": "Enhances up to 2 selected cards to Bonus Cards",
 "lovers": "Enhances 1 selected card to a Wild Card",
 "chariot": "Enhances 1 selected card to a Steel Card",
 "justice": "Enhances 1 selected card to a Glass Card",
 "devil": "Enhances 1 selected card to a Gold Card",
 "tower": "Enhances 1 selected card to a Stone Card",
 "wheel_of_fortune": "1 in 4 chance to add an edition to a random Joker",
}

# bosses implemented in this port (key -> description). Order of the C enum follows this list.
BOSSES = {
 "bl_hook": "Discards 2 random cards per hand played",
 "bl_ox": "Playing your most played hand sets money to $0",
 "bl_wall": "Extra large blind",
 "bl_arm": "Decreases level of played hand",
 "bl_club": "All Clubs are debuffed",
 "bl_goad": "All Spades are debuffed",
 "bl_window": "All Diamonds are debuffed",
 "bl_head": "All Hearts are debuffed",
 "bl_water": "Start with 0 discards",
 "bl_manacle": "-1 hand size",
 "bl_mouth": "Play only 1 hand type this round",
 "bl_eye": "No repeat hand types this round",
 "bl_psychic": "Must play 5 cards",
 "bl_tooth": "Lose $1 per card played",
 "bl_flint": "Base Chips and Mult are halved",
 "bl_plant": "All face cards are debuffed",
 "bl_needle": "Play only 1 hand",
 "bl_serpent": "After play or discard, always draw 3 cards",
 "bl_pillar": "Cards played this ante are debuffed",
 "bl_final_heart": "A random Joker is debuffed each hand",
 "bl_final_leaf": "All cards debuffed until 1 Joker is sold",
 "bl_final_vessel": "Very large blind",
 "bl_final_bell": "Forces 1 card to always be selected",
 "bl_house": "First hand is drawn face down",
 "bl_wheel": "1 in 7 cards get drawn face down",
 "bl_fish": "Cards drawn face down after each hand played",
 "bl_mark": "All face cards are drawn face down",
 "bl_final_acorn": "Shuffles Jokers at the start of the blind",
}

# skip tags carried over (key -> (position in tags.png, description)); order = icon order in VRAM and TG_* enum
TAGS = [
 ("uncommon",   "Next shop has a free Uncommon Joker"),
 ("rare",       "Next shop has a free Rare Joker"),
 ("investment", "Gain $25 after defeating the next Boss Blind"),
 ("boss",       "Rerolls the Boss Blind of this Ante"),
 ("charm",      "Free Mega Arcana Pack now"),
 ("meteor",     "Free Mega Celestial Pack now"),
 ("buffoon",    "Free Mega Buffoon Pack now"),
 ("handy",      "Gain $1 per hand played this run"),
 ("garbage",    "Gain $1 per unused discard this run"),
 ("coupon",     "Initial cards and Packs of the next shop are free"),
 ("juggle",     "+3 hand size on the next round"),
 ("d_six",      "Rerolls start at $0 in the next shop"),
 ("top_up",     "Create up to 2 common Jokers"),
 ("skip",       "Gain $5 per Blind skipped this run"),
 ("orbital",    "Upgrade a random poker hand by 3 levels"),
 ("economy",    "Doubles your money (max +$40)"),
]

# tier-1 vouchers carried over (key, description). One is offered per Ante; each costs $10.
VOUCHERS = [
 ("overstock_norm",   "+1 card slot in the shop"),
 ("clearance_sale",   "All cards and Packs in the shop are 25% off"),
 ("reroll_surplus",   "Rerolls cost $2 less"),
 ("grabber",          "Permanently gain +1 hand per round"),
 ("wasteful",         "Permanently gain +1 discard each round"),
 ("seed_money",       "Raise the interest cap to $50"),
 ("paint_brush",      "+1 hand size"),
 ("tarot_merchant",   "Tarot cards appear more frequently in the shop"),
 ("planet_merchant",  "Planet cards appear more frequently in the shop"),
]
