#!/usr/bin/env python3
"""Original chiptune loop for the PSG (written for this port; it is NOT the game's soundtrack).
Score tokens: note name (A4, C#5...), '-' hold, '.' rest.  Output: src/gen/music_gen.c (note index + period table)."""
import os
ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
def note_index(tok):      # semitones above C1 (index 1 = C1), 0 = rest, 255 = hold
    if tok == '.': return 0
    if tok == '-': return 255
    name, octv = tok[:-1], int(tok[-1])
    return 1 + (octv - 1) * 12 + NAMES.index(name)
def period(idx):          # PSG clock 1789772.5/16 -> period = 111860.8 / f
    f = 32.703 * 2 ** ((idx - 1) / 12.0)
    return int(round(111860.8 / f))

LEAD = ("E5 - C5 - D5 E5 C5 -   A4 - C5 - F5 - E5 C5   G5 - E5 - C5 - D5 E5   D5 - B4 - G4 - B4 D5 "
        "E5 - C5 - D5 E5 G5 -   F5 - A5 - F5 - E5 C5   G5 - E5 - C5 - E5 G5   B5 - A5 - G5 - D5 B4").split()
BASS = ("A2 . A2 . E3 . A2 .   F2 . F2 . C3 . F2 .   C3 . C3 . G3 . C3 .   G2 . G2 . D3 . G2 . "
        "A2 . A2 . E3 . A2 .   F2 . F2 . C3 . F2 .   C3 . C3 . G3 . C3 .   G2 . G2 . B2 . D3 .").split()
assert len(LEAD) == len(BASS) == 64, (len(LEAD), len(BASS))
lead = [note_index(t) for t in LEAD]; bass = [note_index(t) for t in BASS]
maxn = 1 + 6 * 12
with open(os.path.join(ROOT, 'src', 'gen', 'music_gen.c'), 'w') as f:
    f.write('// GENERATED by tools/gen_music.py - original loop composed for this port\n#include "gtypes.h"\n')
    f.write('const u16 g_NotePeriod[%d] = {0,%s};\n' % (maxn + 1, ','.join(str(period(i)) for i in range(1, maxn + 1))))
    f.write('const u8 g_MusicLen = %d;\n' % len(lead))
    f.write('const u8 g_MusicLead[%d] = {%s};\n' % (len(lead), ','.join(map(str, lead))))
    f.write('const u8 g_MusicBass[%d] = {%s};\n' % (len(bass), ','.join(map(str, bass))))
print("music: %d steps" % len(lead))
