#!/usr/bin/env python3
"""Data pipeline: Balatro Lua tables + content.py -> C tables (include/data_gen.h, src/seg/data_s*_b3.c).

Costs, rarities, blind parameters, hand base values and ante scaling are read from the original
Lua source (original/game.lua, functions/misc_functions.lua) so the original stays the source of truth.
Text tables live in a dedicated mapper segment (visible through bank 3)."""
import os, sys, re, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lua_data as L
import content as C

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
OUT_INC = os.path.join(ROOT, 'include'); OUT_SEG = os.path.join(ROOT, 'src', 'seg')
TEXT_SEG = 20

if not L.have_original():
    print("gen_data: ./original not present - keeping committed generated data"); sys.exit(0)

cen = L.centers(); bl = L.blinds()
game = open(os.path.join(L.ORIG, 'game.lua'), encoding='utf8').read()
order = json.load(open(os.path.join(ROOT, 'build', 'blind_order.json')))['blind_order']

def cs(s):  # C string literal
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def enum_name(k): return 'JK_' + k.upper()

# ---- hand table from G.GAME.hands -------------------------------------------------
hands = []
for m in re.finditer(r'\["([^"]+)"\]\s*=\s*\{visible[^}]*?order\s*=\s*(\d+)\s*,\s*mult\s*=\s*(\d+),\s*chips\s*=\s*(\d+),.*?l_mult\s*=\s*(\d+),\s*l_chips\s*=\s*(\d+)', game):
    hands.append((m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4)), int(m.group(5)), int(m.group(6))))
hands.sort(key=lambda h: -h[1])        # ascending value: High Card ... Flush Five
assert len(hands) == 12 and hands[0][0] == 'High Card', hands
ante_amounts = [int(x) for x in re.search(r'local amounts = \{\s*([\d,\s]+)\}', open(os.path.join(L.ORIG, 'functions', 'misc_functions.lua')).read()).group(1).replace('\n', ' ').split(',') if x.strip()]
assert len(ante_amounts) == 8, ante_amounts

hdr = ['// GENERATED by tools/gen_data.py from the original Lua tables - do not edit', '#pragma once', '#include "gtypes.h"', '']
hdr.append('enum { %s, JOKER_COUNT };' % ', '.join(enum_name(k) for k in C.JOKERS))
hdr.append('enum { %s, TAROT_COUNT };' % ', '.join('TR_' + k.upper() for k in C.TAROTS))
bosses = list(C.BOSSES.keys())
hdr.append('enum { %s, BOSS_COUNT };' % ', '.join('BS_' + k[3:].upper() for k in bosses))
hdr.append('enum { HAND_HIGH_CARD, HAND_PAIR, HAND_TWO_PAIR, HAND_THREE, HAND_STRAIGHT, HAND_FLUSH, HAND_FULL_HOUSE, HAND_FOUR, HAND_STRAIGHT_FLUSH, HAND_FIVE, HAND_FLUSH_HOUSE, HAND_FLUSH_FIVE, HAND_COUNT };')
hdr.append('#define ANTE_COUNT 8')
hdr.append('''
typedef struct { const char* name; const char* desc; u8 cost; u8 rarity; u8 cell; } JokerDef;
typedef struct { const char* name; const char* desc; u8 cell; } TarotDef;
typedef struct { const char* name; u8 baseChips; u8 baseMult; u8 lvlChips; u8 lvlMult; u8 cell; } HandDef;
typedef struct { const char* name; const char* desc; u8 mult2; u8 reward; u8 minAnte; u8 icon; } BossDef; // mult2 = target multiplier x2
extern const JokerDef g_Jokers[JOKER_COUNT];
extern const TarotDef g_Tarots[TAROT_COUNT];
extern const HandDef  g_Hands[HAND_COUNT];
extern const BossDef  g_Bosses[BOSS_COUNT];
extern const u16 g_AnteAmount[ANTE_COUNT];
extern const u8 g_BlindIcon[2];   // small, big icon rows
#define JOKER_RARITY_COUNT 3''')
open(os.path.join(OUT_INC, 'data_gen.h'), 'w').write('\n'.join(hdr) + '\n')

# ---- text/data tables in a mapper segment -----------------------------------------
src = ['// GENERATED by tools/gen_data.py from the original Lua tables - do not edit',
       '#include "gtypes.h"', '#include "data_gen.h"', '#include "assets_gen.h"', '']
src.append('const JokerDef g_Jokers[JOKER_COUNT] = {')
for i, k in enumerate(C.JOKERS):
    c = cen['j_' + k]
    src.append('\t{ %s, %s, %d, %d, CELL_JOKER + %d },' % (cs(c['name']), cs(C.JOKER_DESC[k]), int(c['cost']), int(c['rarity']), i))
src.append('};')
src.append('const TarotDef g_Tarots[TAROT_COUNT] = {')
for i, k in enumerate(C.TAROTS):
    src.append('\t{ %s, %s, CELL_TAROT + %d },' % (cs(cen['c_' + k]['name']), cs(C.TAROT_DESC[k]), i))
src.append('};')
src.append('const HandDef g_Hands[HAND_COUNT] = {')
for i, h in enumerate(hands):
    name, order_, mult, chips, lm, lc = h
    src.append('\t{ %s, %d, %d, %d, %d, CELL_PLANET + %d },' % (cs(name), chips, mult, lc, lm, i))
src.append('};')
# planets must be in hand-value order (content.PLANETS is already: pluto=High Card ... eris=Flush Five)
assert [p[1] for p in C.PLANETS] == [h[0] for h in hands], ([p[1] for p in C.PLANETS], [h[0] for h in hands])
src.append('const BossDef g_Bosses[BOSS_COUNT] = {')
for k in bosses:
    b = bl[k]
    src.append('\t{ %s, %s, %d, %d, %d, %d },' % (cs(b['name']), cs(C.BOSSES[k]), int(b['mult'] * 2), b['dollars'], b['min'], order.index(k)))
src.append('};')
src.append('const u16 g_AnteAmount[ANTE_COUNT] = { %s };' % ', '.join(str(a) for a in ante_amounts))
src.append('const u8 g_BlindIcon[2] = { %d, %d };' % (order.index('bl_small'), order.index('bl_big')))
open(os.path.join(OUT_SEG, 'data_s%d_b3.c' % TEXT_SEG), 'w').write('\n'.join(src) + '\n')
print("data: %d jokers, %d tarots, %d bosses, hands %s" % (len(C.JOKERS), len(C.TAROTS), len(bosses), [h[0][:4] for h in hands]))
