#!/usr/bin/env python3
"""Data pipeline: Balatro Lua tables + content.py -> C tables (include/data_gen.h, src/seg/data_s*_b3.c).

Costs, rarities, blind parameters, hand base values and ante scaling are read from the original
Lua source (original/game.lua, functions/misc_functions.lua) so the original stays the source of truth.
Text tables live in a dedicated mapper segment (visible through bank 3)."""
import math, os, sys, re, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lua_data as L
import content as C

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
OUT_INC = os.path.join(ROOT, 'include'); OUT_SEG = os.path.join(ROOT, 'src', 'seg')
TEXT_SEG = 20
DESC_SEG = 21
DESC_SEG2 = 23
DESC_SPLIT = 128                     # descriptions below this index live in segment 21, the rest in segment 23

if not L.have_original():
    print("gen_data: ./original not present - keeping committed generated data"); sys.exit(0)

cen = L.centers(); bl = L.blinds()
game = open(os.path.join(L.ORIG, 'game.lua'), encoding='utf8').read()
order = json.load(open(os.path.join(ROOT, 'build', 'blind_order.json')))['blind_order']

def cs(s):  # C string literal
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def enum_name(k): return 'JK_' + k.upper()

# ---- hand table from G.GAME.hands -------------------------------------------------
hands = []
for m in re.finditer(r'\["([^"]+)"\]\s*=\s*\{visible[^}]*?order\s*=\s*(\d+)\s*,\s*mult\s*=\s*(\d+),\s*chips\s*=\s*(\d+),.*?l_mult\s*=\s*(\d+),\s*l_chips\s*=\s*(\d+)', game):
    hands.append((m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4)), int(m.group(5)), int(m.group(6))))
hands.sort(key=lambda h: -h[1])        # ascending value: High Card ... Flush Five
assert len(hands) == 12 and hands[0][0] == 'High Card', hands
_mf = open(os.path.join(L.ORIG, 'functions', 'misc_functions.lua'), encoding='utf8').read()
ante_tables = []                                 # one table per scaling mode (White/Red stake, Green, Purple)
for blk in re.findall(r'local amounts = \{([^}]*)\}', _mf)[:3]:
    nums = [int(x) for x in re.sub(r'--[^\n]*', '', blk).replace('\n', ' ').split(',') if x.strip()]
    assert len(nums) == 8, nums
    ante_tables.append(nums)
for nums in ante_tables:
    for ante in range(9, 13):                    # endless antes, same formula as get_blind_amount; saturates near the u32 limit
        c = ante - 8; amt = int(nums[7] * (1.6 + (0.75 * c) ** (1 + 0.2 * c)) ** c)
        amt -= amt % (10 ** (int(math.log10(amt)) - 1)); nums.append(min(amt, 0xFFFFFFFF // 4))
ante_amounts = ante_tables[0]

hdr = ['// GENERATED by tools/gen_data.py from the original Lua tables - do not edit', '#pragma once', '#include "gtypes.h"', '']
hdr.append('enum { %s, JOKER_COUNT };' % ', '.join(enum_name(k) for k in C.JOKERS))
hdr.append('enum { %s, TAROT_COUNT };' % ', '.join('TR_' + k.upper() for k in C.TAROTS))
hdr.append('enum { %s, SPECTRAL_COUNT };' % ', '.join('SP_' + k.upper() for k in C.SPECTRALS))
bosses = list(C.BOSSES.keys())
hdr.append('enum { %s, BOSS_COUNT };' % ', '.join('BS_' + k[3:].upper() for k in bosses))
hdr.append('enum { HAND_HIGH_CARD, HAND_PAIR, HAND_TWO_PAIR, HAND_THREE, HAND_STRAIGHT, HAND_FLUSH, HAND_FULL_HOUSE, HAND_FOUR, HAND_STRAIGHT_FLUSH, HAND_FIVE, HAND_FLUSH_HOUSE, HAND_FLUSH_FIVE, HAND_COUNT };')
hdr.append('enum { %s, TAG_COUNT };' % ', '.join('TG_' + k.upper() for k, _ in C.TAGS))
hdr.append('enum { %s, VOUCHER_COUNT };' % ', '.join('VC_' + k.split('_norm')[0].upper() for k, _ in C.VOUCHERS))
hdr.append('#define ANTE_COUNT 12')
hdr.append('#define SEG_DESC %d\n#define SEG_DESC2 %d\n#define DESC_SPLIT %d' % (DESC_SEG, DESC_SEG2, DESC_SPLIT))
hdr.append('''
typedef struct { const char* name; u8 desc; u8 cost; u8 rarity; u8 cell; } JokerDef;       // desc = index into g_Desc (segment 21)
typedef struct { const char* name; u8 desc; u8 cell; } TarotDef;
typedef struct { const char* name; u8 baseChips; u8 baseMult; u8 lvlChips; u8 lvlMult; u8 cell; } HandDef;
typedef struct { const char* name; u8 desc; u8 mult2; u8 reward; u8 minAnte; u8 icon; } BossDef; // mult2 = target multiplier x2\ntypedef struct { const char* name; u8 desc; u8 minAnte; } TagDef;\ntypedef struct { const char* name; u8 desc; u8 cell; } VoucherDef;
extern const JokerDef g_Jokers[JOKER_COUNT];
extern const TarotDef g_Tarots[TAROT_COUNT];\nextern const TarotDef g_Spectrals[SPECTRAL_COUNT];
extern const HandDef  g_Hands[HAND_COUNT];
extern const BossDef  g_Bosses[BOSS_COUNT];\nextern const TagDef   g_Tags[TAG_COUNT];\nextern const VoucherDef g_Vouchers[VOUCHER_COUNT];
extern const u32 g_AnteAmount[3][ANTE_COUNT];
extern const u8 g_BlindIcon[2];   // small, big icon rows
#define JOKER_RARITY_COUNT 3''')
open(os.path.join(OUT_INC, 'data_gen.h'), 'w').write('\n'.join(hdr) + '\n')

# ---- text/data tables in a mapper segment -----------------------------------------
src = ['// GENERATED by tools/gen_data.py from the original Lua tables - do not edit',
       '#include "gtypes.h"', '#include "data_gen.h"', '#include "assets_gen.h"', '']
descs = []
def D(text):
    descs.append(text); return len(descs) - 1
src.append('const JokerDef g_Jokers[JOKER_COUNT] = {')
for i, k in enumerate(C.JOKERS):
    c = cen['j_' + k]
    src.append('\t{ %s, %d, %d, %d, %d },' % (cs(c['name']), D(C.JOKER_DESC[k]), int(c['cost']), int(c['rarity']), i))
src.append('};')
src.append('const TarotDef g_Tarots[TAROT_COUNT] = {')
for i, k in enumerate(C.TAROTS):
    src.append('\t{ %s, %d, CELL_TAROT + %d },' % (cs(cen['c_' + k]['name']), D(C.TAROT_DESC[k]), i))
src.append('};')
src.append('const TarotDef g_Spectrals[SPECTRAL_COUNT] = {')
for i, k in enumerate(C.SPECTRALS):
    src.append('\t{ %s, %d, CELL_SPECTRAL + %d },' % (cs(cen['c_' + k]['name']), D(C.SPECTRAL_DESC[k]), i))
src.append('};')
src.append('const HandDef g_Hands[HAND_COUNT] = {')
for i, h in enumerate(hands):
    name, order_, mult, chips, lm, lc = h
    src.append('\t{ %s, %d, %d, %d, %d, CELL_PLANET + %d },' % (cs(name), chips, mult, lc, lm, i))
src.append('};')
# planets must be in hand-value order (content.PLANETS is already: pluto=High Card ... eris=Flush Five)
assert [p[1] for p in C.PLANETS] == [h[0] for h in hands], ([p[1] for p in C.PLANETS], [h[0] for h in hands])
src.append('const BossDef g_Bosses[BOSS_COUNT] = {')
for k in bosses:
    b = bl[k]
    src.append('\t{ %s, %d, %d, %d, %d, %d },' % (cs(b['name']), D(C.BOSSES[k]), int(b['mult'] * 2), b['dollars'], b['min'], order.index(k)))
src.append('};')
src.append('const TagDef g_Tags[TAG_COUNT] = {')
TAG_MIN = {'handy': 2, 'garbage': 2, 'meteor': 2, 'buffoon': 2, 'top_up': 2, 'orbital': 2}
for k, d in C.TAGS:
    src.append('\t{ %s, %d, %d },' % (cs(cen['tag_' + k]['name'].replace(' Tag', '')), D(d), TAG_MIN.get(k, 1)))
src.append('};')
src.append('const VoucherDef g_Vouchers[VOUCHER_COUNT] = {')
for i, (k, d) in enumerate(C.VOUCHERS):
    src.append('\t{ %s, %d, CELL_VOUCHER + %d },' % (cs(cen['v_' + k]['name']), D(d), i))
src.append('};')
src.append('const u32 g_AnteAmount[3][ANTE_COUNT] = {')
for nums in ante_tables: src.append('\t{ %s },' % ', '.join(str(a) + 'UL' for a in nums))
src.append('};')
src.append('const u8 g_BlindIcon[2] = { %d, %d };' % (order.index('bl_small'), order.index('bl_big')))
src.append('#include "ui/ui_text.c"')
assert len(descs) < 256, len(descs)
for segno, lo, hi, name in ((DESC_SEG, 0, DESC_SPLIT, 'g_Desc'), (DESC_SEG2, DESC_SPLIT, 256, 'g_Desc2')):
    part = descs[lo:hi]
    dsrc = ['// GENERATED by tools/gen_data.py - effect descriptions (mapper segment %d, switched into bank 3 on demand)' % segno, '#include "gtypes.h"', '']
    dsrc.append('const char* const %s[%d] = {' % (name, max(len(part), 1)))
    for t in (part or ['']): dsrc.append('\t%s,' % cs(t))
    dsrc.append('};')
    open(os.path.join(OUT_SEG, 'seg_s%d_b3.c' % segno), 'w').write('\n'.join(dsrc) + '\n')
open(os.path.join(OUT_SEG, 'seg_s%d_b3.c' % TEXT_SEG), 'w').write('\n'.join(src) + '\n')
print("data: %d jokers, %d tarots, %d bosses, hands %s" % (len(C.JOKERS), len(C.TAROTS), len(bosses), [h[0][:4] for h in hands]))
